import type { TransportNotice, TransportTrip, GuestTransportRequest } from "./types";

const today = new Date();
const nextDate = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 45);
const isoDate = nextDate.toISOString().slice(0, 10);

export const transportTripsMock: TransportTrip[] = [
  {
    id: "trip-bus-hotel-ida",
    titulo: "Bus hoteles centro -> finca",
    nombre: "Bus hoteles centro",
    origen: "Hoteles centro de Sevilla",
    destino: "Finca La Encina",
    fecha: isoDate,
    horaSalida: "17:15",
    horaLlegadaEstimada: "17:50",
    hora: "17:15",
    tipoTransporte: "bus",
    plazasDisponibles: 52,
    plazasOcupadas: 31,
    capacidad: 52,
    requiereReserva: true,
    precioOpcional: 0,
    puntoEncuentro: "Puerta principal Hotel Alameda",
    responsable: "Lucía - wedding planner",
    contacto: "+34 600 123 123",
    observaciones: "Pensado para invitados alojados en el centro. Salida puntual.",
    notas: "Subida 15 minutos antes.",
    estado: "activo",
  },
  {
    id: "trip-microbus-vuelta-noche",
    titulo: "Microbús finca -> hoteles centro",
    nombre: "Microbús vuelta noche",
    origen: "Finca La Encina",
    destino: "Hoteles centro de Sevilla",
    fecha: isoDate,
    horaSalida: "02:15",
    horaLlegadaEstimada: "02:45",
    hora: "02:15",
    tipoTransporte: "microbus",
    plazasDisponibles: 24,
    plazasOcupadas: 24,
    capacidad: 24,
    requiereReserva: true,
    precioOpcional: 0,
    puntoEncuentro: "Zona parking principal",
    responsable: "Miguel - coordinación",
    contacto: "+34 600 222 333",
    observaciones: "Segundo vehículo de vuelta. Actualmente completo.",
    notas: "Lista de espera abierta.",
    estado: "completo",
  },
  {
    id: "trip-transfer-estacion",
    titulo: "Transfer estación AVE -> ceremonia",
    nombre: "Transfer estación",
    origen: "Estación Santa Justa",
    destino: "Iglesia San Miguel",
    fecha: isoDate,
    horaSalida: "16:40",
    horaLlegadaEstimada: "17:00",
    hora: "16:40",
    tipoTransporte: "transfer",
    plazasDisponibles: 8,
    plazasOcupadas: 3,
    capacidad: 8,
    requiereReserva: true,
    precioOpcional: 12,
    puntoEncuentro: "Parada taxis salida principal",
    responsable: "Jesús - familia novio",
    contacto: "+34 600 888 111",
    observaciones: "Ideal para invitados que llegan en el AVE de la tarde.",
    notas: "",
    estado: "activo",
  },
];

export const transportRequestsMock: GuestTransportRequest[] = [
  {
    id: "req-carmen",
    guestToken: "guest-carmen-mora",
    guestName: "Carmen Mora",
    transportId: "trip-bus-hotel-ida",
    seats: 2,
    notes: "Volvemos también al centro.",
    needsTransport: true,
    direction: "ambas",
    origin: "Hotel Alameda",
    peopleCount: 2,
    reducedMobility: false,
    childSeat: false,
    comments: "Nos interesa también la vuelta si ampliáis plazas.",
    status: "solicitado",
    hasCarOffer: false,
    offeredSeats: 0,
    createdAt: Date.now() - 1000 * 60 * 60 * 30,
    updatedAt: Date.now() - 1000 * 60 * 60 * 2,
  },
  {
    id: "req-david",
    guestToken: "guest-david-arias",
    guestName: "David Arias",
    transportId: "trip-transfer-estacion",
    seats: 1,
    notes: "",
    needsTransport: true,
    direction: "ida",
    origin: "Estación Santa Justa",
    peopleCount: 1,
    reducedMobility: true,
    childSeat: false,
    comments: "Necesito apoyo para acceso sencillo.",
    status: "pendiente",
    hasCarOffer: false,
    offeredSeats: 0,
    createdAt: Date.now() - 1000 * 60 * 60 * 18,
    updatedAt: Date.now() - 1000 * 60 * 60 * 4,
  },
  {
    id: "req-marta",
    guestToken: "guest-marta-ruiz",
    guestName: "Marta Ruiz",
    transportId: "",
    seats: 1,
    notes: "Salimos desde Dos Hermanas.",
    needsTransport: false,
    direction: "ambas",
    origin: "Dos Hermanas",
    peopleCount: 1,
    reducedMobility: false,
    childSeat: false,
    comments: "Tengo coche y puedo llevar a 3 personas.",
    status: "resuelto",
    hasCarOffer: true,
    offeredSeats: 3,
    approximateSchedule: "Salida 16:30 / vuelta tras recena",
    createdAt: Date.now() - 1000 * 60 * 60 * 40,
    updatedAt: Date.now() - 1000 * 60 * 60 * 5,
  },
  {
    id: "req-raul",
    guestToken: "guest-raul-vila",
    guestName: "Raúl Vila",
    transportId: "",
    seats: 2,
    notes: "",
    needsTransport: false,
    direction: "vuelta",
    origin: "Mairena del Aljarafe",
    peopleCount: 2,
    reducedMobility: false,
    childSeat: true,
    comments: "Puedo llevar 2 plazas libres de vuelta.",
    status: "asignado",
    hasCarOffer: true,
    offeredSeats: 2,
    approximateSchedule: "Solo trayecto de vuelta",
    createdAt: Date.now() - 1000 * 60 * 60 * 26,
    updatedAt: Date.now() - 1000 * 60 * 60 * 3,
  },
  {
    id: "req-laura",
    guestToken: "guest-laura-mena",
    guestName: "Laura Mena",
    transportId: "",
    seats: 3,
    notes: "Venimos con un niño.",
    needsTransport: true,
    direction: "ida",
    origin: "Hotel Catedral",
    peopleCount: 3,
    reducedMobility: false,
    childSeat: true,
    comments: "Si no hay bus, nos interesa coche compartido.",
    status: "sin_solucion",
    hasCarOffer: false,
    offeredSeats: 0,
    createdAt: Date.now() - 1000 * 60 * 60 * 20,
    updatedAt: Date.now() - 1000 * 60 * 55,
  },
];

export const transportNoticesMock: TransportNotice[] = [
  {
    id: "notice-1",
    titulo: "Punto de encuentro actualizado",
    mensaje: "El bus del centro saldrá finalmente desde la puerta principal del Hotel Alameda.",
    tipo: "importante",
    fechaHora: `${isoDate}T12:30`,
    trayectoRelacionado: "trip-bus-hotel-ida",
  },
  {
    id: "notice-2",
    titulo: "Microbús de vuelta completo",
    mensaje: "El microbús de las 02:15 está completo. Estamos valorando abrir un segundo vehículo.",
    tipo: "urgente",
    fechaHora: `${isoDate}T18:00`,
    trayectoRelacionado: "trip-microbus-vuelta-noche",
  },
  {
    id: "notice-3",
    titulo: "Transfer estación disponible",
    mensaje: "Si llegas en el AVE de la tarde, reserva cuanto antes el transfer para asegurar plaza.",
    tipo: "info",
    fechaHora: `${isoDate}T09:15`,
    trayectoRelacionado: "trip-transfer-estacion",
  },
];
